import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/antd.registry';
import MainListItems from '../app/component/menu/mainMenu';
import { colors } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MenuLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: 'flex', flexDirection: 'row', width: '100%' }}>
          {/* Menu */}
          <div style={{   color:'white',flex: 1.5  }}>
            <div>
              <MainListItems />
            </div>
          </div>
          {/* Data */}
          <div style={{ flex: 8.5 }}>
            <StyledComponentsRegistry>
              {children}
            </StyledComponentsRegistry>
          </div>
        </div>
      </body>
    </html>
  )
}
